---
# vars file for certbot-ssl-management
certbot_challenge: dns
certbot_email: myemail@email.com
certbot_domain: mydomain.com
certbot_letsencrypt: "{{ certbot_path }}/letsencrypt-auto certonly --manual --email {{ certbot_email }} --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d *.{{ certbot_domain }} --preferred-challenges={{ certbot_challenge }}"
