---
# tasks file for dns-management

# install dns (bind)
- name: install bind
  yum: 
    name: "{{ dns_packages }}"
    state: latest
- name: configure firewall
  firewalld: 
    service: "{{ item }}"
    state: enabled
    permanent: true
    zone: public
  notify: restart_firewalld
  loop: "{{ dns_firewall_services }}"
- name: enable named
  service: 
    name: "{{ dns_service }}"
    enabled: true
    state: started

# configure dns (bind zones)
- name: configure /etc/named.conf
  template: 
    src: named.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0640'
- name: configure forward-zone
  template: 
    src: forward-zone.j2
    dest: "/var/named/{{ dns_forward_zone_file }}"
    owner: root
    group: named
    mode: '0640'
- name: configure reverse-zone
  template:
    src: reverse-zone.j2
    dest: "/var/named/{{ dns_reverse_zone_file }}"
    owner: root
    group: named
    mode: '0640'
  notify: restart_named
