---
- name: register host (red hat subscription manager)
  become: true
  hosts: "{{ target_hosts }}"
  vars: 
  tasks: 
    - name: install katello-ca-consumer
      yum:
        name: qemu-guest-agent
        state: present
