---
# tasks file for remote-authorization
- name: create remote user 
  user: 
    name: "{{ ansible_user_name }}"
    comment: Ansible SSH Machine User
    group: wheel
    password: "{{ ansible_user_password | password_hash('sha512') }}"
- name: validate and/or create .ssh directory
  file:
    path: "/home/{{ ansible_user_name }}/.ssh/"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user_name }}"
    group: wheel
- name: copy remote user rsa public key
  authorized_key:
    user: "{{ ansible_user_name }}"
    state: present
    key: "{{ ansible_public_key }}"
- name: configure 'wheel' group for no password sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
