---
# tasks file for subscription-management
- include_vars: rhn-info.yml
- name: subscription-manager register --auto-attach
  redhat_subscription:
    state: present
    username: "{{ rhn_user_name }}"
    password: "{{ rhn_user_password }}"
    auto_attach: true
