---
- name: install + register red hat insights
  hosts: "{{ target_host }}"
  tasks: 
    - name: install insights-client
      yum: 
        name: insights-client
        state: latest
    - name: register insights-client
      command: insights-client --register
