---
# tasks file for certbot-ssl-management
- name: install git
  yum: 
    name: git
    state: latest
- name: create /opt/certbot
  file: 
    path: "{{ certbot_path }}"
    state: directory
- name: git clone certbot
  git: 
    repo: "{{ certbot_git_repo }}"
    dest: "{{ certbot_path }}"
- debug:
    msg: "Execute '{{ certbot_letsencrypt }}' on '{{ target_host }}' to generate SSL certificate"
