---
- name: install bind dns requirements
  hosts: "{{ target_host }}"
  include: dns-config.yml
  tasks:

    - name: install bind
      yum: 
        name: "{{ item }}"
        state: latest
      with_items: "{{ dns_packages }}"

    - name: configure firewall
      firewalld: 
        service: dns
        state: enabled
        permanent: true
        zone: public
      notify: restart_firewalld

    - name: enable named
      service: 
        name: named
        enabled: true
        state: started

  handlers:
    - name: restart_firewalld
      service:
        name: firewalld
        state: restarted
