---
- name: install bind dns requirements
  hosts: "{{ target_host }}"
  become: true
  vars_files: dns-config.yml
  tasks:
    - name: install bind
      yum: 
        name: "{{ dns_packages }}"
        state: latest
    - name: configure firewall
      firewalld: 
        service: dns
        state: enabled
        permanent: true
        zone: public
      notify: restart_firewalld
    - name: enable named
      service: 
        name: named
        enabled: true
        state: started
  handlers:
    - name: restart_firewalld
      service:
        name: firewalld
        state: restarted
