---
- hosts: all
  become: yes
  become_method: sudo
  vars_files: 
    - satellite-info.yml
  tasks:
    - name: download / install Satellite CA Certificate
      yum:
        disable_gpg_check: yes
        name: "https://{{ satellite_url }}{{ satellite_cert_url }}"
        state: present
    - name: register 
      redhat_subscription:
        state: present
        activationkey: "{{ satellite_act_key }}"
        org_id: "{{ satellite_org_id }}"
      when:
        - ansible_distribution_major_version == "8"
    - name: install katello-agent
      yum:
        name: katello-host-tools
        state: present
